minecraft_version=1.20.1
forge_version=47.3.0
mod_id=arcane_bridge
mod_version=1.0.2
mod_group_id=com.example.arcanebridge
org.gradle.java.home=C:/Program Files/Java/jdk-17

# Выделение памяти И обход блокировки прокси объединены в одну шину аргументов
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Djdk.http.auth.tunneling.disabledSchemes=""

