modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="arcane_bridge"
version="1.0.0"
displayName="Arcane Bridge"
authors="go1den"
description="Ethereal Armor Bridge"
mainClass="com.example.arcanebridge.ArcaneBridge"

[[dependencies.arcane_bridge]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcane_bridge]]
modId="curios"
mandatory=true
versionRange="[5.0,)"
ordering="NONE"
side="BOTH"